"""create challenges table

Revision ID: ae204ca02d9c
Revises: f093dc53691c
Create Date: 2026-06-14 14:54:12.423673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae204ca02d9c'
down_revision: Union[str, Sequence[str], None] = 'f093dc53691c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('TREE_PLANTATION', 'RECYCLING', 'WATER_CONSERVATION', 'ENERGY_SAVING', 'CLEANUP_DRIVE', 'SUSTAINABLE_TRANSPORT', 'COMMUNITY_SERVICE', name='challenge_category', native_enum=False), nullable=False),
    sa.Column('challenge_type', sa.Enum('SOLO', 'COMMUNITY', name='challenge_type', native_enum=False), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='challenge_difficulty', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'AI_GENERATED', 'APPROVED', 'PUBLISHED', 'COMPLETED', name='challenge_status', native_enum=False), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenges')
    # ### end Alembic commands ###
